const BooksDetails = [
    {
        bookId: 1,
        bookTitle: 'Zen: The Art of Simple Living [Hardcover] Masuno, Shunmyo Hardcover',
        Author: 'Shunmyo Masuno',
        category: 'Self-Help',
        description: 'Be more Zen in 2022 with this little book of 100 tips and activities to soothe the soul Brings the spirit of Zen Buddhism to everyday life . . . 100 snack-size Zen activities you can do daily to add more calm to your life Daily Telegraph Zen is the perfect antidote to the stress and uncertainty of modern life . . .In clear practical and easy to follow lessons - one a day for 100 days - renowned Buddhist monk Shunmyo Masuno draws on centuries of wisdom to show you how to apply the essence of Zen to modern life. You will learn how to exhale deeply to eliminate negative emotions, to arrange your house simply to clear your thinking, to line up your shoes at night to bring order to your mind, to plant a single flower and watch it grow, to worry less about what you cannot control, and so much more . . . You will even make time to think about nothing at all. Simplify your life with the art of Zen, and learn how to feel more relaxed, fulfilled, and with a renewed sense of peace.',
        ImageUrl: 'https://m.media-amazon.com/images/I/71HWrm777DL._SL1500_.jpg',
        price: 100,
        originalPrice: 250,
        discountPercentage: 20,
        amount: 1,
        rating: 4.5
    },
    {
        bookId: 2,
        bookTitle: 'Revenge of the Tipping Point | Hardcover – 3 October 2024',
        Author: 'Malcolm Gladwell',
        category: 'Psychology',
        description: 'Twenty-five years after the publication of his groundbreaking first book, Malcolm Gladwell returns with a brand new volume that reframes the lessons of The Tipping Point in a startling and revealing light Why in the late 1980s and early 90s did Los Angeles become the bank robbery capital of the world? What is the Magic Third and what does it have to do with racial equity? What do big cats and clusters of teen suicides have in common? These are just some of the questions Malcolm Gladwell addresses in this new work, which revisits the phenomenon of epidemics and examines the ways in which we have learned to tinker with and shape the spread of ideas, viruses, and trends-sometimes with great success, sometimes with disastrous consequences',
        ImageUrl: 'https://odyssey.in/cdn/shop/files/revengeofthetipping_600x.jpg?v=1726930889',
        price: 200,
        originalPrice: 300,
        discountPercentage: 25,
        amount: 1,
        rating: 5
    },
    {
        bookId: 3,
        bookTitle: 'An Eye for an Eye -Paperback - 24 September 2024',
        Author: 'Jeffrey Archer',
        category: 'Thriller',
        description: 'The unputdownable new novel from international bestseller Jeffrey Archer In one of the most luxurious cities on earth… A billion-dollar deal is about to go badly wrong. A lavish night out is about to end in murder. And the British government is about to be plunged into crisis.In the heart of the British establishment…Lord Hartley, the latest in a line of peers going back over two hundred years, lies dying. But his will triggers an inheritance with explosive consequences.Two deaths. Continents apart. No obvious connection.So why are they both at the centre of a master criminals plot for revenge? And can Scotland Yards elite squad uncover the truth before its too late…',
        ImageUrl: 'https://i.harperapps.com/hcanz/covers/9780008640132/x293.jpg',
        price: 150,
        originalPrice: 200,
        discountPercentage: 30,
        amount: 1,
        rating: 4
    },
    {
        bookId: 4,
        bookTitle: 'Diary of a Wimpy Kid: Hot Mess (Book 19)',
        Author: ' Jeff Kinney',
        category: 'Children',
        description: 'In Hot Mess, book 19 of the Diary of a Wimpy Kid series from #1 international bestselling author Jeff Kinney, Greg Heffley is in for a particularly awkward summer with his whole family. When the Heffleys agree to spend summer break with both Mum’s and Dad’s relatives at the same time, they have to figure out how to be in two places at once. With Greg caught in the middle, can the Heffleys pull off the ultimate scheme? Or will their vacation turn into a hilarious hot mess? This sidesplittingly relatable summer story is the funniest Wimpy Kid book yet! WHATS IN DIARY OF A WIMPY KID? 50% words, 50% cartoons, 100% hilarious! Stories that all readers cant wait to get their hands on Laughter guaranteed! Have you read all the DIARY OF A WIMPY KID books? Diary of a Wimpy Kid (#1) | Rodrick Rules (#2) | The Last Straw (#3) | Dog Days (#4) | The Ugly Truth (#5) | Cabin Fever (#6) | The Third Wheel (#7) | Hard Luck (#8) | The Long Haul (#9) | Old School (#10) | Double Down (#11) | The Getaway (#12) | The Meltdown (#13) | Wrecking Ball (#14) | The Deep End (#15) | Big Shot (#16) | Diper Överlöde (#17) | No Brainer (#18) | Hot Mess (#19)',
        ImageUrl: 'https://m.media-amazon.com/images/I/51dX2kFl25L._SY445_SX342_.jpg',
        price: 259,
        originalPrice: 400,
        discountPercentage: 35,
        amount: 1,
        rating: 4.5
    },
    {
        bookId: 5,
        bookTitle: 'Before We Forget Kindness',
        Author: 'Toshikazu Kawaguchi',
        category: 'Fiction',
        description: 'In the fifth book in the sensational Before the Coffee Gets Cold series, the mysterious café where customers arrive hoping to travel back in time welcomes four new guests: - The father who could not allow his daughter to get married - A woman who couldnt give Valentines Day chocolates to her loved one - A boy who wants to show his smile to his divorced parents - A wife holding a child with no name . . . They must follow the cafés strict rules, however, and come back to the present before their coffee goes cold. In another moving and heartwarming tale from Toshikazu Kawaguchi, our new visitors wish to go back into their past to move on their present, finding closure and comfort so they can embark on a beautiful future.',
        ImageUrl: 'https://books.google.co.in/books/publisher/content?id=p8jeEAAAQBAJ&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U1ug8gjHXDTYpOrceB4pgYEzTK8-w&w=1280',
        price: 50,
        originalPrice: 150,
        discountPercentage: 70,
        amount: 1,
        rating: 5
    },
    {
        bookId: 6,
        bookTitle: 'IKIGAI : The Japanese secret to a long and happy life',
        category: 'Self-Help',
        Author: 'Francesc Miralles',
        description: 'We all have an ikigai.Its the Japanese word for ‘a reason to live’ or ‘a reason to jump out of bed in the morning’.Its the place where your needs, desires, ambitions, and satisfaction meet. A place of balance. Small wonder that finding your ikigai is closely linked to living longer.Finding your ikigai is easier than you might think. This book will help you work out what your own ikigai really is, and equip you to change your life. You have a purpose in this world: your skills, your interests, your desires and your history have made you the perfect candidate for something. All you have to do is find it.Do that, and you can make every single day of your life joyful and meaningful.I read it and it’s bewitched me ever since. I’m spellbound.’Chris Evans Ikigai gently unlocks simple secrets we can all use to live long, meaningful, happy lives. Science-based studies weave beautifully into honest, straight-talking conversation you won’t be able to put down. Warm, patient, and kind, this book pulls you gently along your own journey rather than pushing you from behind. Neil Pasricha, bestselling author of The Happiness Equation',
        ImageUrl: 'https://images3.penguinrandomhouse.com/cover/9780143130727',
        price: 90,
        originalPrice: 200,
        discountPercentage: 60,
        amount: 1,
        rating: 4.5
    },
    {
        bookId: 7,
        bookTitle: 'The Silent Patient',
        Author: 'Alex Michaelides',        
        category: 'Psychological Thriller',
        description: 'WITH OVER THREE MILLION COPIES SOLD, read the Sunday Times and No.1 New York Times bestselling, record-breaking thriller that everyone is talking about - soon to be a major film. The perfect thriller AJ FINN Terrific - THE TIMES Crime Book of the Month Smart, sophisticated suspense - LEE CHILD Compelling - OBSERVER Absolutely brilliant - STEPHEN FRY A totally original psychological mystery - DAVID BALDACCI One of the best thrillers Ive read this year - CARA HUNTER The pace and finesse of a master - BBC CULTURE Alicia Berenson lived a seemingly perfect life until one day six years ago.When she shot her husband in the head five times. Since then she hasnt spoken a single word.Its time to find out why. THE SILENT PATIENT is the gripping must-read thriller of the year - perfect for fans of THE FAMILY UPSTAIRS by Lisa Jewell, BLOOD ORANGE by Harriet Tyce and PLAYING NICE by JP Delaney.',
        ImageUrl: 'https://images.squarespace-cdn.com/content/v1/58349ff3f7e0ab6c8636f24c/1558953255237-PWIYS50P0H2VXM7C4FJU/ke17ZwdGBToddI8pDm48kG92JA5s_olOPKiIAZEOzq17gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1UQ9OE6Nok5Z1d9SznKouZjJ7DVboibDynoZcL_2chHL_Skf28yxfMn4Vem2XljIbPg/81zTPgET%2BnL.jpg',
        price: 200,
        originalPrice: 400,
        discountPercentage: 40,
        amount: 1,
        rating: 3.5
    },
    {
        bookId: 8,
        bookTitle: 'Atomic Habits',
        Author: 'James Clear',
        category: 'Self-Improvement',
        description: 'THE PHENOMENAL INTERNATIONAL BESTSELLER: OVER 1O MILLION COPIES SOLD WORLDWIDE Transform your life with tiny changes in behaviour  starting now. People think that when you want to change your life  you need to think big. But world-renowned habits expert James Clear has discovered another way. He knows that real change comes from the compound effect of hundreds of small decisions: doing two push-ups a day  waking up five minutes early  or holding a single short phone call. He calls them atomic habits. In this ground-breaking book  Clears reveals exactly how these minuscule changes can grow into such life-altering outcomes. He uncovers a handful of simple life hacks (the forgotten art of Habit Stacking  the unexpected power of the Two Minute Rule  or the trick to entering the Goldilocks Zone)  and delves into cutting-edge psychology and neuroscience to explain why they matter. Along the way  he tells inspiring stories of Olympic gold medalists  leading CEOs  and distinguished scientists who have used the science of tiny habits to stay productive  motivated  and happy.These small changes will have a revolutionary effect on your career  your relationships  and your life. A NEW YORK TIMES AND SUNDAY TIMES BESTSELLER A supremely practical and useful book.  Mark Manson  author of The Subtle Art of Not Giving A F*ck James Clear has spent years honing the art and studying the science of habits. This engaging  hands-on book is the guide you need to break bad routines and make good ones.  Adam Grant  author of Original Atomic Habits is a step-by-step manual for changing routines.  Books of the Month  Financial Times A special book that will change how you approach your day and live your life.  Ryan Holiday  author of The Obstacle is the Way',
        ImageUrl: 'https://m.media-amazon.com/images/I/419aJfhczCL._SY445_SX342_.jpg',
        price: 300,
        originalPrice: 500,
        discountPercentage: 35,
        amount: 1,
        rating: 5
    },
    {
        bookId: 9,
        bookTitle: 'SAPIENS : A Brief History of Humankind',
        Author: 'Yuval Noah Harari',
        category: 'History',
        description: '**THE MILLION COPY BESTSELLER** Interesting and provocative... It gives you a sense of how briefly we ve been on this Earth  Barack Obama What makes us brilliant? What makes us deadly? What makes us Sapiens? Yuval Noah Harari challenges everything we know about being human in the perfect read for these unprecedented times. Earth is 4.5 billion years old. In just a fraction of that time  one species among countless others has conquered it: us. In this bold and provocative book  Yuval Noah Harari explores who we are  how we got here and where we re going.  I would recommend Sapiens to anyone who s interested in the history and future of our species  Bill Gates **ONE OF THE GUARDIAN S 100 BEST BOOKS OF THE 21st CENTURY**',
        ImageUrl: 'https://books.google.co.in/books/publisher/content?id=1EiJAwAAQBAJ&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U2nf4ZzBE_NFma6-FTPoPwEmL0_oA&w=1280',
        price: 120,
        originalPrice: 250,
        discountPercentage: 50,
        amount: 1,
        rating: 4
    },
    {
        bookId: 10,
        bookTitle: 'PERENN IAL SELLER',
        Author: 'Ryan Holiday',
        category: 'Business',
        description: 'Bestselling author and marketing strategist Ryan Holiday reveals to creatives of all stripes-authors, entrepreneurs, musicians, filmmakers, fine artists-how a classic work is made and marketed.< Perennial Seller he takes us back to the first principles of the models and thinking that underpin the creation of something built to last. Featuring interviews with some of the world;s greatest entrepreneurs and creatives and grounded in a deep study of the classics from every genre, the book shares a mindset and approach we can all adopt to make and market a classic work. Whether you have a book or a business, a song or the next great screenplay, Holiday reveals the recipe for perennial success.',
        ImageUrl: 'https://books.google.co.in/books/publisher/content?id=X-VwDgAAQBAJ&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U1hQ36b7DLIzAp3tNuRdbgQDh-5zA&w=1280',
        price: 180,
        originalPrice: 400,
        discountPercentage: 50,
        amount: 1,
        rating: 3.5
    },
    {
        bookId: 11,
        bookTitle: 'CONSPIRACY',
        Author: 'Ryan Holiday',
        category: 'Politics',
        description: 'Conspiracy theories are legion. Conspiracies are rare. And of the few that do exist  fewer are ever discovered  let alone explained. This story is the exception. In 2016  media giant Gawker was forced to declare bankruptcy after a $140 million dollar judgment in court over an illegally recorded sex tape of Hulk Hogan. The case was no accident: it was the result of a nearly decade-long plot masterminded by Facebook and Paypal billionaire Peter Thiel.With exclusive access to all the key players  Ryan Holiday takes us behind the scenes of this extraordinary and at times surreal story  and transforms the events into both a dissection of that controversial methodology - conspiracy - and an eye-opening cautionary tale on the use  abuse and consequences of power and secrecy in the modern age.',
        ImageUrl: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1511922947i/36681909.jpg',
        price: 210,
        originalPrice: 400,
        discountPercentage: 55,
        amount: 1,
        rating: 4.5
    },
    {
        bookId: 12,
        bookTitle: 'RIGHT THING RIGHT NOW',
        Author: 'Ryan Holiday',
        category: 'Self-Help',
        description: 'THE #1 NEW YORK TIMES BESTSELLER - HOW TO HARNESS THE LIFE-CHANGING POWER OF INTEGRITY A message all of us need to hear  Arnold Schwarzenegger This book is a gift to humanity  Dr. Edith Eva Eger For the Stoics  justice was more than an idea. It was a way of life  a personal commitment to doing the right thing  no matter how difficult the path.Our ability to live by our values and do good is life-changing; it is key to self-respect  purpose and success on our own terms. In this third instalment of his bestselling Stoic Virtues series  Ryan Holiday draws on historical icons and contemporary heroes to show us how to embrace the power of owning our convictions and acting accordingly in an era of dishonesty. Ultimately  the path to greatness is impossible without goodness.Your values  your character and your deeds determine your success and your legacy. This book shows you the way.',
        ImageUrl: 'https://m.media-amazon.com/images/I/51-JeQrw26L._SY445_SX342_.jpg',
        price: 70,
        originalPrice: 300,
        discountPercentage: 80,
        amount: 1,
        rating: 5
    },
    {
        bookId: 13,
        bookTitle: 'DISCIPLINE IS DESTINY',
        Author: 'RYAN HOLIDAY',
        category: 'Motivational',
        description: 'To master anything, we must first master ourselves: our emotions, thoughts and actions. This ancient virtue of self-control is more essential than ever. In this bestselling book, Ryan Holiday makes the case for this essential virtue, and shows how to cultivate willpower, self-respect and focus. From Marcus Aurelius to Toni Morrison, Queen Elizabeth II to Martin Luther King Jr, historys greats have all understood the power of directing your habits and setting your limits. Historys cautionary tales prove the same point, from catastrophic military overreaches to career-destroying habits: without self-discipline, we are lost before we can even begin. Self-discipline is the key to our greatest ambitions and simplest joys: this book will show you how to find it, apply it and reap the rewards.',
        ImageUrl: 'https://m.media-amazon.com/images/I/51rnDyeUmPL._SY445_SX342_.jpg',
        price: 500,
        originalPrice: 1999,
        discountPercentage: 65,
        amount: 1,
        rating: 4.5
    },
    {
        bookId: 14,
        bookTitle: 'FUN WITH FESTIVALS',
        Author: 'Na',
        category: 'Children',
        description: 'Now enjoy your favourite festival even more with myths  legends and fun things to do throughout the year! From Diwali s dazzle to Holi s hues  from Navratri s beats to Eid s feasts and from Christmas carols to New Year treats  get set to rejoice with your loved ones. Packed with festive facts  wonderful things to make  and exciting activities to do with friends and family  this delightful book has everything you need to turn each day into a cheerful celebration It s all here! So why wait?Learn to make your favourite goodies  help your folks decorate the house  make DIY gifts for your friends  and dig into this super one-stop celebration collection to create cherished memories.',
        ImageUrl: 'https://m.media-amazon.com/images/I/51KhwiA7ElL._SY445_SX342_.jpg',
        price: 450,
        originalPrice: 800,
        discountPercentage: 50,
        amount: 1,
        rating: 4.5
    },
    {
        bookId: 15,
        bookTitle: 'EASY OCEAN ORIGAMI',
        Author: 'Christopher L. Harbo',
        category: 'Hobby',
        description: 'Do you love the ocean? Now you can create your own paper sea with Easy Ocean Origami. With a few simple folds you’ll make a blue whale, a sail boat, a windsurfer, and so much more. Grab some paper and start folding!',
        ImageUrl: 'https://m.media-amazon.com/images/I/5135ZBQYhFL._SX342_SY445_.jpg',
        price: 350,
        originalPrice: 999,
        discountPercentage: 60,
        amount: 1,
        rating: 3
    },
    {
        bookId: 16,
        bookTitle: 'Zen: The Art of Simple Living [Hardcover] Masuno, Shunmyo Hardcover',
        Author: 'Shunmyo Masuno',
        category: 'Self-Help',
        description: 'Be more Zen in 2022 with this little book of 100 tips and activities to soothe the soul Brings the spirit of Zen Buddhism to everyday life . . . 100 snack-size Zen activities you can do daily to add more calm to your life Daily Telegraph Zen is the perfect antidote to the stress and uncertainty of modern life . . .In clear practical and easy to follow lessons - one a day for 100 days - renowned Buddhist monk Shunmyo Masuno draws on centuries of wisdom to show you how to apply the essence of Zen to modern life. You will learn how to exhale deeply to eliminate negative emotions, to arrange your house simply to clear your thinking, to line up your shoes at night to bring order to your mind, to plant a single flower and watch it grow, to worry less about what you cannot control, and so much more . . . You will even make time to think about nothing at all. Simplify your life with the art of Zen, and learn how to feel more relaxed, fulfilled, and with a renewed sense of peace.',
        ImageUrl: 'https://m.media-amazon.com/images/I/71HWrm777DL._SL1500_.jpg',
        price: 140,
        originalPrice: 250,
        discountPercentage: 30,
        amount: 1,
        rating: 4.5
    },
    {
        bookId: 17,
        bookTitle: 'Diary of a Wimpy Kid: Hot Mess (Book 19)',
        Author: ' Jeff Kinney',
        category: 'Children',
        description: 'In Hot Mess, book 19 of the Diary of a Wimpy Kid series from #1 international bestselling author Jeff Kinney, Greg Heffley is in for a particularly awkward summer with his whole family. When the Heffleys agree to spend summer break with both Mum’s and Dad’s relatives at the same time, they have to figure out how to be in two places at once. With Greg caught in the middle, can the Heffleys pull off the ultimate scheme? Or will their vacation turn into a hilarious hot mess? This sidesplittingly relatable summer story is the funniest Wimpy Kid book yet! WHATS IN DIARY OF A WIMPY KID? 50% words, 50% cartoons, 100% hilarious! Stories that all readers cant wait to get their hands on Laughter guaranteed! Have you read all the DIARY OF A WIMPY KID books? Diary of a Wimpy Kid (#1) | Rodrick Rules (#2) | The Last Straw (#3) | Dog Days (#4) | The Ugly Truth (#5) | Cabin Fever (#6) | The Third Wheel (#7) | Hard Luck (#8) | The Long Haul (#9) | Old School (#10) | Double Down (#11) | The Getaway (#12) | The Meltdown (#13) | Wrecking Ball (#14) | The Deep End (#15) | Big Shot (#16) | Diper Överlöde (#17) | No Brainer (#18) | Hot Mess (#19)',
        ImageUrl: 'https://m.media-amazon.com/images/I/51dX2kFl25L._SY445_SX342_.jpg',
        price: 340,
        originalPrice: 600,
        discountPercentage: 35,
        amount: 1,
        rating: 4
    },
    {
        bookId: 18,
        bookTitle: 'Revenge of the Tipping Point | Hardcover – 3 October 2024',
        Author: 'Malcolm Gladwell',
        category: 'Psychology',
        description: 'Twenty-five years after the publication of his groundbreaking first book, Malcolm Gladwell returns with a brand new volume that reframes the lessons of The Tipping Point in a startling and revealing light Why in the late 1980s and early 90s did Los Angeles become the bank robbery capital of the world? What is the Magic Third and what does it have to do with racial equity? What do big cats and clusters of teen suicides have in common? These are just some of the questions Malcolm Gladwell addresses in this new work, which revisits the phenomenon of epidemics and examines the ways in which we have learned to tinker with and shape the spread of ideas, viruses, and trends-sometimes with great success, sometimes with disastrous consequences',
        ImageUrl: 'https://odyssey.in/cdn/shop/files/revengeofthetipping_600x.jpg?v=1726930889',
        price: 190,
        originalPrice: 450,
        discountPercentage: 50,
        amount: 1,
        rating: 5
    },
    {
        bookId: 19,
        bookTitle: 'The Silent Patient',
        Author: 'Alex Michaelides',
        category: 'Psychological Thriller',
        description: 'WITH OVER THREE MILLION COPIES SOLD, read the Sunday Times and No.1 New York Times bestselling, record-breaking thriller that everyone is talking about - soon to be a major film. The perfect thriller AJ FINN Terrific - THE TIMES Crime Book of the Month Smart, sophisticated suspense - LEE CHILD Compelling - OBSERVER Absolutely brilliant - STEPHEN FRY A totally original psychological mystery - DAVID BALDACCI One of the best thrillers Ive read this year - CARA HUNTER The pace and finesse of a master - BBC CULTURE Alicia Berenson lived a seemingly perfect life until one day six years ago.When she shot her husband in the head five times. Since then she hasnt spoken a single word.Its time to find out why. THE SILENT PATIENT is the gripping must-read thriller of the year - perfect for fans of THE FAMILY UPSTAIRS by Lisa Jewell, BLOOD ORANGE by Harriet Tyce and PLAYING NICE by JP Delaney.',
        ImageUrl: 'https://images.squarespace-cdn.com/content/v1/58349ff3f7e0ab6c8636f24c/1558953255237-PWIYS50P0H2VXM7C4FJU/ke17ZwdGBToddI8pDm48kG92JA5s_olOPKiIAZEOzq17gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1UQ9OE6Nok5Z1d9SznKouZjJ7DVboibDynoZcL_2chHL_Skf28yxfMn4Vem2XljIbPg/81zTPgET%2BnL.jpg',
        price: 270,
        originalPrice: 700,
        discountPercentage: 60,
        amount: 1,
        rating: 4
    },
    {
        bookId: 20,
        bookTitle: 'SAPIENS : A Brief History of Humankind',
        Author: 'Yuval Noah Harari',
        category: 'History',
        description: '**THE MILLION COPY BESTSELLER** Interesting and provocative... It gives you a sense of how briefly we ve been on this Earth  Barack Obama What makes us brilliant? What makes us deadly? What makes us Sapiens? Yuval Noah Harari challenges everything we know about being human in the perfect read for these unprecedented times. Earth is 4.5 billion years old. In just a fraction of that time  one species among countless others has conquered it: us. In this bold and provocative book  Yuval Noah Harari explores who we are  how we got here and where we re going.  I would recommend Sapiens to anyone who s interested in the history and future of our species  Bill Gates **ONE OF THE GUARDIAN S 100 BEST BOOKS OF THE 21st CENTURY**',
        ImageUrl: 'https://books.google.co.in/books/publisher/content?id=1EiJAwAAQBAJ&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U2nf4ZzBE_NFma6-FTPoPwEmL0_oA&w=1280',
        price: 50,
        originalPrice: 150,
        discountPercentage: 80,
        amount: 1,
        rating: 4.5
    }

]

export default BooksDetails;